version: "3.8"

services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:9000
      - WATCHPACK_POLLING=true
    volumes:
      - ../..:/app
      - /app/node_modules
      - /app/apps/web/.next
    command: yarn workspace @code-project/web dev

networks:
  default:
    name: code-project-network
    driver: bridge
