module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        nunito: ['var(--font-nunito)', 'sans-serif'],
      },
      fontSize: {
        h1: ['36px', {lineHeight: '44px', fontWeight: '700'}],
        h2: ['28px', {lineHeight: '36px', fontWeight: '700'}],
        h3: ['24px', {lineHeight: '28px', fontWeight: '700'}],
        'subtitle-semibold-lg': [
          '20px',
          {lineHeight: '24px', fontWeight: '600'},
        ],
        'subtitle-lg': ['20px', {lineHeight: '24px', fontWeight: '400'}],
        'subtitle-italic-lg': [
          '20px',
          {lineHeight: '24px', fontWeight: '400', fontStyle: 'italic'},
        ],
        'body-bold-lg': ['18px', {lineHeight: '24px', fontWeight: '700'}],
        'body-semibold-aa-lg': [
          '18px',
          {lineHeight: '24px', fontWeight: '600'},
        ],
        'body-semibold-lg': ['18px', {lineHeight: '24px', fontWeight: '600'}],
        'body-medium-lg': ['18px', {lineHeight: '24px', fontWeight: '500'}],
        'body-lg': ['18px', {lineHeight: '24px', fontWeight: '400'}],

        'subtitle-semibold': ['18px', {lineHeight: '28px', fontWeight: '600'}],
        subtitle: ['18px', {lineHeight: '24px', fontWeight: '400'}],
        'subtitle-italic': [
          '18px',
          {lineHeight: '24px', fontWeight: '400', fontStyle: 'italic'},
        ],
        'body-bold': ['16px', {lineHeight: '24px', fontWeight: '700'}],
        'body-semibold-aa': ['16px', {lineHeight: '24px', fontWeight: '600'}],
        'body-semibold': ['16px', {lineHeight: '24px', fontWeight: '600'}],
        'body-medium': ['16px', {lineHeight: '24px', fontWeight: '500'}],
        body: ['16px', {lineHeight: '24px', fontWeight: '400'}],
      },
      colors: {
        white: '#FFFFFF',
        dark: '#0E0800',
        bg: '#F9F9F9',
        'main-yellow': '#F9C74F',
        'yellow-hover': '#F0B62B',
        'secondary-orange': '#E99714',
        'txt-secondary': '#7B7875',
        placeholder: '#9E9E9E',
        additional: '#7A5A36',
        'brown-dark': '#563817',
        'dark-stroke': '#312F2D',
        stroke: '#E0DCD2',
        'light-grey': '#F3F3F3',
        grey: '#EBEBEB',
        disable: '#E0E0E0',
        info: '#3256D8',
        danger: '#E92B2B',
        'light-orange': '#FEF4DC',
        green: '#00983D',
        'burnt-sienna': '#A64D2F',
        brand: {
          primary: '#F9C74F',
          'primary-hover': '#F0B62B',
          secondary: '#E99714',
          dark: '#0E0800',
          light: '#F9F9F9',
        },
      },
    },
  },
  plugins: [],
};
