services:
  cp-main:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    ports:
      - '9000:9000'
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=local
      - PORT=9000
    depends_on:
      cp-main-db:
        condition: service_healthy
      cp-main-redis:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/cp-main/src

  cp-main-db:
    image: postgres:17
    restart: always
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=cp-main-db
      - POSTGRES_USER=admin
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d cp-main-db']
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    
  cp-main-redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6381:6379'
    command: redis-server --appendonly yes --requirepass redispass
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: